spring:
  datasource:
    url: jdbc:h2:file:C:/practicalJava/graffitishop/src/main/resources/graffitishop
    username: user
    password: user
  jpa:
    generate-ddl: false
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none


  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:

      # Включить все конечные точки
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    # Включить экспорт prometheus
    metrics:
      export:
        prometheus:
          enabled: true
      # включить гистограмму на основе процентилей для http запросов
      distribution:
        percentiles-histogram:
          "[http.server.requests]": true
      # сегментов гистограммы http SLA
      sla:
        http:
          server:
            requests: 1ms,5ms
      # включить метрики JVM
      enable:
        jvm: true

info:
  application:
    name: graffitishop
    description: graffitishop
    artifact: graffitishop
    version: 0.0.1-SNAPSHOT
  techstack:
    java: open jdk 8
    spring boot: 2.5.1
    database: H2
    kafka: